### ISSUE TITLE
Plugin breaking payment method detail view in admin due to "billieConfig" extension not being loaded

### ISSUE THREAD

**Issue by patchee500** [ozean12/shopware6-module#11]
When navigating to any (both billie and non-billie) payment method's detail view in the Shopware admin, an error is thrown, interrupting the rest of the view to load.  

The error is the following:  

![image](https://user-images.githubusercontent.com/8124315/193593566-9a6a1642-daae-43e2-aae4-de244d68c8e9.png)

It seems to be connected to the "billieConfig" PaymentMethod Extension not being available in the corresponding template (/src/Resources/app/administration/src/module/sw-settings-payment/page/sw-settings-payment-detail/sw-settings-payment-detail.html.twig)

**Comment by rommelfreddy** [comment]
hello @patchee500 

can you tell me more about your environment?
This issue is not known.

**Comment by patchee500** [comment]
Sorry, this was from a long time ago and not a very critical issue. It no longer seems to appear in newer Shopware/Plugin versions and can therefore be ignored.
